/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface EditorComponent {
      'first': string;
      'last': string;
    }
  }

  interface HTMLEditorComponentElement extends StencilComponents.EditorComponent, HTMLStencilElement {}

  var HTMLEditorComponentElement: {
    prototype: HTMLEditorComponentElement;
    new (): HTMLEditorComponentElement;
  };
  interface HTMLElementTagNameMap {
    'editor-component': HTMLEditorComponentElement;
  }
  interface ElementTagNameMap {
    'editor-component': HTMLEditorComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'editor-component': JSXElements.EditorComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface EditorComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;